version: "3"

volumes:
  cache_storage:
    name: test_volume

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TG_STYLE_BOT_TOKEN=${TG_STYLE_BOT_TOKEN}
    volumes:
      - "cache_storage:/storage"
    restart: always
