version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TG_STYLE_BOT_TOKEN=${TG_STYLE_BOT_TOKEN}
    volumes:
      - "/storage:/storage"
    restart: always
