name: Python tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black mypy pytest
      - name: Check PEP8 compliance
        run: |
          black --check --verbose TransferBot
        continue-on-error: true # TODO: change to false
      - name: Lint with mypy
        run: |
          mypy TransferBot
        continue-on-error: true # TODO: change to false
      - name: Install package
        run: pip install -e .
      - name: Unit tests with pytest
        run: |
          pytest ./tests
