name: Python tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup env
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v4
        name: Cache env
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install --only dev
      - name: Check with flake8
        run: poetry run flake8 --max-line-length=121 --ignore=W605,F401 transferbot/
      - name: Check with ruff
        run: poetry run ruff --output-format=github --config ./pyproject.toml .
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup env
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v4
        name: Cache env
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install
      - name: Test coverage (Total)
        run: poetry run pytest -v --cov=transferbot tests/test_bot.py
      - name: Test coverage (Handlers)
        run: poetry run pytest -v --junitxml=pytest.xml --cov=transferbot/bot/ --cov-fail-under=90 tests/test_bot.py | tee pytest-coverage.txt
